# Site settings
author: William Pannell
title: code blog :-)
header-img: img/home-bg.png
email: lpann5@gmail.com
copyright_name: William Pannell
description: > # this means to ignore newlines until "baseurl:"
  my experience coding with flatiron
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  junkmail7

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
